
DROP DATABASE IF EXISTS `PHI`;
CREATE DATABASE  IF NOT EXISTS `PHI`;
USE `PHI`;

--
--
--

ALTER TABLE Public_Housing_Inspections
MODIFY INSPECTION_DATE DATE;

DROP TABLE IF EXISTS A3Q5_PHA;

CREATE TABLE A3Q5_PHA AS
SELECT A.PHA_NAME, A.MR_INSPECTION_DATE, A.MR_INSPECTION_COST, A.SECOND_MR_INSPECTION_DATE,
A.SECOND_MR_INSPECTION_COST, A.CHANGE_IN_COST, A.PERCENT_CHANGE_IN_COST
FROM (SELECT DISTINCT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME, 
		LEAD(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
		LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST,
		INSPECTION_DATE AS MR_INSPECTION_DATE,
		COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
		COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC)) AS CHANGE_IN_COST,
		((COST_OF_INSPECTION_IN_DOLLARS - (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC))) / COST_OF_INSPECTION_IN_DOLLARS) * 100 AS PERCENT_CHANGE_IN_COST,
		ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS FLAG
FROM Public_Housing_Inspections) AS A
WHERE A.MR_INSPECTION_COST > A.SECOND_MR_INSPECTION_COST AND A.SECOND_MR_INSPECTION_DATE IS NOT NULL AND FLAG = 1;

SELECT * FROM A3Q5_PHA;
